[general]
name = "subprocess"
version = "0.1.6"

[build]
files = ["subprocess.fix"]
objects = ["lib.o"]
preliminary_commands = [["make", "lib.o"]]
library_paths = ["."]

[build.test]
files = ["test.fix"]
memcheck = true
debug = true
