[general]
name = "subprocess"
version = "1.0.4"
description = "Provides a way to run subprocesses."

[build]
files = ["subprocess.fix"]
objects = ["lib.o"]
preliminary_commands = [["make", "lib.o"]]
library_paths = ["."]

[build.test]
files = ["test.fix"]
memcheck = true
debug = true
